// Develop job for this library.
//
// NOT LIVE YET, and it has TODOs. See library_release.groovy's header for the activation steps and
// the filename rules, and ../seed/README.md for the one-time bootstrap that applies this file.
//
// Branch discovery only - builds on every push to a branch matching the filter below. Runs this
// repo's cicd/jenkins/Jenkinsfile, which reads env.BRANCH_NAME to tell this apart from a release
// build and publishes <Version>-dev.<BUILD_NUMBER>. main is deliberately not discovered: releases
// come from tags.

// TODO: confirm the App folder - must match library_release.groovy exactly, or the pair ends up in
// two different Jenkins folders.
folder('DMNSN') {
    displayName('DMNSN')
}
folder('DMNSN/Libraries') {
    displayName('Libraries')
}
folder('DMNSN/Libraries/DMNSN.Templates.NugetLibrary') {
    displayName('DMNSN.Templates.NugetLibrary')
}

multibranchPipelineJob('DMNSN/Libraries/DMNSN.Templates.NugetLibrary/develop') {
    displayName('develop')
    description('''
        Auto-generated by the DMNSN.IaC.Jenkins seed job.
        Do not edit this job's config in the Jenkins UI - changes will be overwritten the next
        time the seed job runs. Edit the .groovy file and commit instead.
    '''.stripIndent().trim())

    branchSources {
        branchSource {
            source {
                github {
                    id('DMNSN.Templates.NugetLibrary-develop-github')
                    configuredByUrl(false)
                    // TODO: point these three at the real repository.
                    repositoryUrl('https://github.com/DevilDogTG/DMNSN.Templates.NugetLibrary')
                    repoOwner('DevilDogTG')
                    repository('DMNSN.Templates.NugetLibrary')
                    credentialsId('github-pat')

                    traits {
                        // strategyId(1) skips branches that are also open as a PR, avoiding
                        // building the same commit twice under two names.
                        gitHubBranchDiscovery {
                            strategyId(1)
                        }
                        headRegexFilter {
                            // Unscoped is correct for a single-component repo. If this repo ever
                            // hosts several publishable components, scope each one's filter to its
                            // own branch prefix - otherwise every component builds on every push.
                            regex('^(feature/.*|bugfix/.*)$')
                        }
                    }
                }
            }

            strategy {
                // Empty props = default auto-trigger. noTriggerBranchProperty() would suppress the
                // build branch-api schedules on discovery, which is the point of this job.
                defaultBranchPropertyStrategy {
                    props {}
                }
            }
        }
    }

    factory {
        workflowBranchProjectFactory {
            scriptPath('cicd/jenkins/Jenkinsfile')
        }
    }

    orphanedItemStrategy {
        discardOldItems {
            numToKeep(20)
        }
    }

    triggers {
        periodicFolderTrigger {
            interval('1d')
        }
    }
}
