// Release job for this library.
//
// NOT LIVE YET, and it has TODOs. A job definition only reaches Jenkins when a seed job applies it.
// This repo carries its own seed job - see ../seed/README.md. To activate:
//
//   1. Fill in the TODOs below (repo owner/name, and the folder this library belongs under).
//      ../jobs/library_develop.groovy must use the SAME folder, or the pair splits in two.
//   2. Complete the one-time bootstrap in ../seed/README.md.
//   3. Re-run the seed job after any change to this file - editing it alone does nothing.
//
// Filenames here take lowercase and underscores ONLY - no dots, no hyphens. Job DSL derives a Groovy
// class name from the filename and neither is valid in one. So a project named Foo.Bar.Baz would use
// foo_bar_baz_release.groovy. The Jenkins job NAME below can contain dots freely.
//
// Tag discovery only - builds exactly when a tag matching vX.Y.Z is pushed. Runs this repo's
// cicd/jenkins/Jenkinsfile, which reads env.TAG_NAME to tell this apart from a develop build,
// asserts the tag equals <Version> in the library csproj, then packs and publishes.

// TODO: confirm the App folder. Libraries are grouped under DMNSN/Libraries by default; change it
// if this library belongs to an existing application grouping.
folder('DMNSN') {
    displayName('DMNSN')
}
folder('DMNSN/Libraries') {
    displayName('Libraries')
}
folder('DMNSN/Libraries/DMNSN.Templates.NugetLibrary') {
    displayName('DMNSN.Templates.NugetLibrary')
}

multibranchPipelineJob('DMNSN/Libraries/DMNSN.Templates.NugetLibrary/release') {
    displayName('release')
    description('''
        Auto-generated by the DMNSN.IaC.Jenkins seed job.
        Do not edit this job's config in the Jenkins UI - changes will be overwritten the next
        time the seed job runs. Edit the .groovy file and commit instead.
    '''.stripIndent().trim())

    branchSources {
        branchSource {
            source {
                github {
                    id('DMNSN.Templates.NugetLibrary-release-github')
                    // Both fields are mandatory on this instance's github-branch-source version
                    // even though only one mode is used.
                    configuredByUrl(false)
                    // TODO: point these three at the real repository. The repo name is assumed to
                    // match the project name, which is often but not always true.
                    repositoryUrl('https://github.com/DevilDogTG/DMNSN.Templates.NugetLibrary')
                    repoOwner('DevilDogTG')
                    repository('DMNSN.Templates.NugetLibrary')
                    // Username/password (a PAT) - reused for API discovery and HTTPS checkout. For
                    // SSH checkout instead, add a real SSH-key credential and an sshCheckoutTrait;
                    // do not point sshCheckoutTrait at a username/password credential.
                    credentialsId('github-pat')

                    traits {
                        // Tags only. headRegexFilter applies to every discovered head, and with no
                        // branch discovery the only heads are tags.
                        gitHubTagDiscovery()
                        headRegexFilter {
                            regex('^v\\d+\\.\\d+\\.\\d+$')
                        }
                    }
                }
            }

            strategy {
                defaultBranchPropertyStrategy {
                    props {}
                }
            }

            // Required for tags. branch-api's default with no buildStrategies is "auto-build
            // everything EXCEPT tags": the tag is discovered, passes its filter, then is skipped
            // with "No automatic build triggered for <tag>". Both ages at '-1' = no restriction.
            // Needs the basic-branch-build-strategies plugin.
            buildStrategies {
                buildTags {
                    atLeastDays('-1')
                    atMostDays('-1')
                }
            }
        }
    }

    factory {
        workflowBranchProjectFactory {
            scriptPath('cicd/jenkins/Jenkinsfile')
        }
    }

    orphanedItemStrategy {
        discardOldItems {
            // numToKeep(int), not numToKeepStr(String) - the String variant is rejected by the
            // Job DSL sandbox.
            numToKeep(20)
        }
    }

    triggers {
        periodicFolderTrigger {
            interval('1d')
        }
    }
}
