// Release job for this library.
//
// DRAFT - NOT LIVE, and it has TODOs. Jenkins applies job definitions only from the seed job in
// DMNSN.IaC.Jenkins, which globs `jobs/**/*.groovy` in THAT repo. To activate:
//
//   1. Fill in the TODOs below (repo owner/name, and the App folder this library belongs under).
//   2. Copy to DMNSN.IaC.Jenkins/jobs/DMNSN/<App>/<component>_release.groovy
//      Rename the file to your component: lowercase, underscores only - NO dots and NO hyphens.
//      Job DSL derives a Groovy class name from the filename, and neither is valid there.
//      e.g. DMNSN.Templates.NugetLibrary -> dmnsn_templates_nugetlibrary_release.groovy
//   3. Let the seed job run.
//
// Tag discovery only - builds exactly when a tag matching vX.Y.Z is pushed. Runs this repo's
// cicd/jenkins/Jenkinsfile, which reads env.TAG_NAME to tell this apart from a develop build,
// asserts the tag equals <Version> in the library csproj, then packs and publishes.

// TODO: confirm the App folder. Libraries are grouped under DMNSN/Libraries by default; change it
// if this library belongs to an existing application grouping.
folder('DMNSN') {
    displayName('DMNSN')
}
folder('DMNSN/Libraries') {
    displayName('Libraries')
}
folder('DMNSN/Libraries/DMNSN.Templates.NugetLibrary') {
    displayName('DMNSN.Templates.NugetLibrary')
}

multibranchPipelineJob('DMNSN/Libraries/DMNSN.Templates.NugetLibrary/release') {
    displayName('release')
    description('''
        Auto-generated by the DMNSN.IaC.Jenkins seed job.
        Do not edit this job's config in the Jenkins UI - changes will be overwritten the next
        time the seed job runs. Edit the .groovy file and commit instead.
    '''.stripIndent().trim())

    branchSources {
        branchSource {
            source {
                github {
                    id('DMNSN.Templates.NugetLibrary-release-github')
                    // Both fields are mandatory on this instance's github-branch-source version
                    // even though only one mode is used.
                    configuredByUrl(false)
                    // TODO: point these three at the real repository. The repo name is assumed to
                    // match the project name, which is often but not always true.
                    repositoryUrl('https://github.com/DevilDogTG/DMNSN.Templates.NugetLibrary')
                    repoOwner('DevilDogTG')
                    repository('DMNSN.Templates.NugetLibrary')
                    // Username/password (a PAT) - reused for API discovery and HTTPS checkout. For
                    // SSH checkout instead, add a real SSH-key credential and an sshCheckoutTrait;
                    // do not point sshCheckoutTrait at a username/password credential.
                    credentialsId('github-pat')

                    traits {
                        // Tags only. headRegexFilter applies to every discovered head, and with no
                        // branch discovery the only heads are tags.
                        gitHubTagDiscovery()
                        headRegexFilter {
                            regex('^v\\d+\\.\\d+\\.\\d+$')
                        }
                    }
                }
            }

            strategy {
                defaultBranchPropertyStrategy {
                    props {}
                }
            }

            // Required for tags. branch-api's default with no buildStrategies is "auto-build
            // everything EXCEPT tags": the tag is discovered, passes its filter, then is skipped
            // with "No automatic build triggered for <tag>". Both ages at '-1' = no restriction.
            // Needs the basic-branch-build-strategies plugin.
            buildStrategies {
                buildTags {
                    atLeastDays('-1')
                    atMostDays('-1')
                }
            }
        }
    }

    factory {
        workflowBranchProjectFactory {
            scriptPath('cicd/jenkins/Jenkinsfile')
        }
    }

    orphanedItemStrategy {
        discardOldItems {
            // numToKeep(int), not numToKeepStr(String) - the String variant is rejected by the
            // Job DSL sandbox.
            numToKeep(20)
        }
    }

    triggers {
        periodicFolderTrigger {
            interval('1d')
        }
    }
}
