// Develop job for the DMNSN.Templates.NugetLibrary template pack.
//
// DRAFT - NOT LIVE. Jenkins only applies job definitions from the seed job in DMNSN.IaC.Jenkins,
// which globs `jobs/**/*.groovy` in THAT repo. To activate, copy this file to:
//     DMNSN.IaC.Jenkins/jobs/DMNSN/Templates/nugetlibrary_develop.groovy
// See cicd/jenkins/jobs/README.md.
//
// Branch discovery only - builds on every push to a branch matching the filter below. Runs this
// repo's cicd/jenkins/Jenkinsfile, which reads env.BRANCH_NAME to tell this apart from a release
// build and publishes <Version>-dev.<BUILD_NUMBER>. main is deliberately not discovered: releases
// come from tags, matching DMNSN.IaC.Jenkins ADR 0002.

folder('DMNSN') {
    displayName('DMNSN')
}
folder('DMNSN/Templates') {
    displayName('Templates')
}
folder('DMNSN/Templates/nugetlibrary') {
    displayName('nugetlibrary')
}

multibranchPipelineJob('DMNSN/Templates/nugetlibrary/develop') {
    displayName('develop')
    description('''
        Auto-generated by the DMNSN.IaC.Jenkins seed job from
        jobs/DMNSN/Templates/nugetlibrary_develop.groovy.
        Do not edit this job's config in the Jenkins UI - changes will be overwritten the next
        time the seed job runs. Edit the .groovy file and commit instead.
    '''.stripIndent().trim())

    branchSources {
        branchSource {
            source {
                github {
                    id('nugetlibrary-develop-github')
                    configuredByUrl(false)
                    repositoryUrl('https://github.com/DevilDogTG/DMNSN.Templates.NugetLibrary')
                    repoOwner('DevilDogTG')
                    repository('DMNSN.Templates.NugetLibrary')
                    credentialsId('github-pat')

                    traits {
                        // Branches only - no gitHubTagDiscovery trait. strategyId(1) skips branches
                        // that are also open as a PR, avoiding building the same commit twice under
                        // two names.
                        gitHubBranchDiscovery {
                            strategyId(1)
                        }
                        headRegexFilter {
                            // Unscoped feature/bugfix is correct here: this repo hosts one
                            // component. The BuildImages jobs scope their filters to an image
                            // prefix only because several components share one source repo there,
                            // so a bare filter would make every component build on every push.
                            regex('^(feature/.*|bugfix/.*)$')
                        }
                    }
                }
            }

            strategy {
                defaultBranchPropertyStrategy {
                    props {}
                }
            }
        }
    }

    factory {
        workflowBranchProjectFactory {
            scriptPath('cicd/jenkins/Jenkinsfile')
        }
    }

    orphanedItemStrategy {
        discardOldItems {
            numToKeep(20)
        }
    }

    triggers {
        periodicFolderTrigger {
            interval('1d')
        }
    }
}
