// Release job for the DMNSN.Templates.NugetLibrary template pack.
//
// DRAFT - NOT LIVE. Jenkins only applies job definitions from the seed job in DMNSN.IaC.Jenkins,
// which globs `jobs/**/*.groovy` in THAT repo. Nothing under this repo's cicd/jenkins/jobs/ is read
// by Jenkins. To activate, copy this file to:
//     DMNSN.IaC.Jenkins/jobs/DMNSN/Templates/nugetlibrary_release.groovy
// and let the seed job run. It lives here so the definition is drafted and reviewed alongside the
// pipeline it launches; see cicd/jenkins/jobs/README.md for the drift tradeoff that implies.
//
// Tag discovery only - builds exactly when a tag matching vX.Y.Z is pushed. Runs this repo's
// cicd/jenkins/Jenkinsfile, which reads env.TAG_NAME to tell this apart from a develop build,
// asserts the tag matches <Version> in the packaging csproj, then packs, verifies, smoke-tests and
// publishes the template pack.
//
// Filename note: underscores, not hyphens. Job DSL derives a Groovy class name from each script's
// filename and hyphens are invalid there. The Jenkins job NAME below can use them freely.

// Job DSL does not auto-create ancestor folders for a '/'-path job name. Declaring an existing
// folder again is idempotent - it just updates it - which is why the release/develop pair can both
// declare the same three.
folder('DMNSN') {
    displayName('DMNSN')
}
folder('DMNSN/Templates') {
    displayName('Templates')
}
folder('DMNSN/Templates/nugetlibrary') {
    displayName('nugetlibrary')
}

multibranchPipelineJob('DMNSN/Templates/nugetlibrary/release') {
    displayName('release')
    description('''
        Auto-generated by the DMNSN.IaC.Jenkins seed job from
        jobs/DMNSN/Templates/nugetlibrary_release.groovy.
        Do not edit this job's config in the Jenkins UI - changes will be overwritten the next
        time the seed job runs. Edit the .groovy file and commit instead.
    '''.stripIndent().trim())

    branchSources {
        branchSource {
            source {
                github {
                    id('nugetlibrary-release-github')
                    // Both fields are mandatory on this instance's github-branch-source version
                    // even though only one mode is used.
                    configuredByUrl(false)
                    repositoryUrl('https://github.com/DevilDogTG/DMNSN.Templates.NugetLibrary')
                    repoOwner('DevilDogTG')
                    repository('DMNSN.Templates.NugetLibrary')
                    credentialsId('github-pat')

                    traits {
                        // Tags only - no gitHubBranchDiscovery trait. headRegexFilter applies to
                        // every discovered head, and with no branch discovery the only heads are
                        // tags, so this filters them to the release-tag pattern.
                        gitHubTagDiscovery()
                        headRegexFilter {
                            // Plain vX.Y.Z per GLOBAL_AGENT 6.9. No component prefix: unlike
                            // DMNSN.IaC.BuildImages, this repo hosts exactly one publishable
                            // component, so there are no sibling components to disambiguate from.
                            regex('^v\\d+\\.\\d+\\.\\d+$')
                        }
                    }
                }
            }

            strategy {
                // Empty props = default auto-trigger. noTriggerBranchProperty() would suppress the
                // build branch-api schedules on discovery, which is the point of this job.
                defaultBranchPropertyStrategy {
                    props {}
                }
            }

            // Required for tags specifically. branch-api's default with no buildStrategies is
            // "auto-build everything EXCEPT tags" - a discovered tag passes its filter and is then
            // skipped with "No automatic build triggered for <tag>" in the indexing log. Both ages
            // at '-1' means no restriction, opting tags back into auto-build on every push.
            // Needs the basic-branch-build-strategies plugin (present in plugins.txt).
            buildStrategies {
                buildTags {
                    atLeastDays('-1')
                    atMostDays('-1')
                }
            }
        }
    }

    factory {
        workflowBranchProjectFactory {
            scriptPath('cicd/jenkins/Jenkinsfile')
        }
    }

    orphanedItemStrategy {
        discardOldItems {
            // numToKeep(int), not numToKeepStr(String) - the String variant is rejected by the
            // Job DSL sandbox.
            numToKeep(20)
        }
    }

    triggers {
        // Fallback re-scan in case the GitHub webhook is missed or misconfigured.
        periodicFolderTrigger {
            interval('1d')
        }
    }
}
